Force rebuild due to bot issue
Build: https://flathub.org/builds/#/builders/31/builds/173

stdio:

Dependency Sdk: org.kde.Sdk 5.10
FB: Running: flatpak --user info org.kde.Sdk/x86_64/5.10 --show-commit
FB: Running: flatpak --user update --subpath= org.kde.Sdk/x86_64/5.10
Looking for updates...
error: GPG signatures found, but none are in trusted keyring
Error running (null): Child process exited with code 1
program finished with exit code 1
elapsedTime=0.316090